package com.ryanantkowiak.ProjectEuler;

/*
Even Fibonacci numbers
Problem 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms. 
*/

public class Problem_00002
{
	public static void main(String[] args)
	{
		long a = 0;
		long b = 1;

		long sum = 0;

		while (b <= 4000000)
		{
			if (b % 2 == 0)
				sum += b;

			long tmp = b;
			b = a + b;
			a = tmp;
		}

		System.out.println(sum);
	}
}

/*
 * 4613732
 */
